### ISSUE TITLE
SSL Certificate not signed by a standard certificate authority 

### ISSUE THREAD

**Issue by visch** [apache/groovy-website#10]
Replicate, go to https://groovy-lang.org/api.html in the latest version of chrome and look at the HTTPS status.

I'll dive into this tonight and see if I can't help move the needle on this.

**Comment by paulk-asert** [comment]
Fixing the user site is a couple of steps away. I may not get to look at it for some weeks. Next step is getting dev site properly automatic. In the groovy-website repo there is a gradle build which produces the site zip. We need to add another task to check that into the groovy-dev-site repo as a fresh check in. We can probably reuse some task defns from the groovy-release repo. It will need someone with Apache credentials to test.

Fixing the user site will then be a replication of this but with a bit more work first and won't build a total replacement but additions for each release as well as some content which is replaced whenever we rebuild the site. Plus we need to liaise with Apache infra to get the new site in place...

**Comment by paulk-asert** [comment]
Groovy's repos are here:
https://gitbox.apache.org/repos/asf
and most mirrored on github.

Currently the :site-dev:generateSite task in the groovy-website repo is used to build the dev site. I manually copy the generated content into the groovy-dev-site (asf-site branch) and then commit.
We have tasks in the groovy-release gradle build files that do such git operations.

**Comment by visch** [comment]
I understand the problem now, messed with things. Unfortunately only had 20 minutes this morning. 


Next steps:

1.  follow groovy-releases lead to get the groovy-website site-dev:generateSite build to publish (copy groovy-website/site-dev/build/site$ to the groovy-dev-site (branch asf-site)  repo
2. Add a site-dev:publishSite task to groovy-website with env variables for apache creds (test with local git creds)

This weekend looks much more promising for me to have time to do this (if someone else can beat me feel free).


What I"m unsure about is how auto publishing impacts the SSL cert being updated on . Is there some way we can short cut all of this to just get the SSL cert updated? 
Maybe we could push some notice up to the main site to say "use http://www.groovy-lang.org/ while we're in process updating the site hosting provider" 

I'll follow regardless as I'm sure there's reasons, let me know if there's anything else I can do!

**Comment by paulk-asert** [comment]
We still need to move the site but for now we have an SSL certificate in place using https://letsencrypt.org/getting-started/.
