### ISSUE TITLE
Groovy CI status

### ISSUE THREAD

**Issue by wololock** [apache/groovy-website#12]
I just wanted to ask about current Groovy CI server status. The documentation and [the website](http://groovy-lang.org/buildstatus.html) mentions  http://ci.groovy-lang.org as a currently used continuous integration server. It seems to be down for some time - all statuses and badges are broken. I guess Travis CI is the tool that [is used at the moment](https://travis-ci.org/apache/groovy). If this is true - what do you think about updating build statuses to use Travis CI badges and links, instead of Team City server that is down? I would like to volunteer, find all occurrences of the Team City build status links and replace them with the working Travis CI links and badges. Please let me know what do you think about it.

**Comment by paulk-asert** [comment]
It was also affected by our disk crash from a little while ago. On my list to look at but won't be this week.

**Comment by wololock** [comment]
Got it, thanks @paulk-asert! Please let us know if there is anything we could help you with, in this area :+1:

**Comment by paulk-asert** [comment]
I'm super keen for more assistance but won't have time to do hand-over for a week in any case.

**Comment by wololock** [comment]
Roger that. I will keep watching it, and I will be ready to help at any time that works for you best.

**Comment by paulk-asert** [comment]
Should be back up and running, so you can close this. We lost some of the original projects during the restore but we can add those in manually as we have time.
