### ISSUE TITLE
refinement needed to handle https and iframes

### ISSUE THREAD

**Issue by paulk-asert** [apache/groovy-website#15]
We have three pages which use layouts/iframedoc.groovy:

gdk.groovy
api.groovy
singlepagedocumentation.groovy

When displaying those pages using http, they work correctly. When using https, the appear as blank pages. a https page won't allow embedded content from a http page. We should tweak that.

**Comment by paulk-asert** [comment]
I hand edited the respective pages, so they are currently working but that will regress when we next build the site. So, we still need to fix this.

**Comment by visch** [comment]
https://groovy-lang.org/single-page-documentation.html is broken again :(

**Comment by paulk-asert** [comment]
fixed again  - manually

**Comment by paulk-asert** [comment]
updated so that no manual fixing is now needed
