### ISSUE TITLE
gpars-meets-virtual-threads blog code errors 

### ISSUE THREAD

**Issue by namuller30** [apache/groovy-website#47]
I was trying to implement the code in the [gpars-meets-virtual-threads article ](https://groovy.apache.org/blog/gpars-meets-virtual-threads) and noticed it doesn't work.

The problem is you need to use the `GParsExecutorsPool.withExistingPool` instead of `GParsPool.withPool` that is listed

**Comment by paulk-asert** [comment]
`GParsPool.withPool` is used for the first example to show GPars using normal threads. The `withExistingPool` method is indeed in the `GParsExecutorsPool` class. It is assumed that folks would find it without too much trouble but you are right it could be clearer to explicitly mention that.

**Comment by paulk-asert** [comment]
Clarified. Thanks for the suggestion.
