### ISSUE TITLE
Signing up to the mailing list results in a 404 error

### ISSUE THREAD

**Issue by dtt101** [apache/groovy-website#7]
To recreate:

1. Visit: http://groovy-lang.org/groovy-weekly.html
2. Complete the form and press subscribe

Result:

The browser redirects to a 404 at the following URL, https://us4.list-manage.com/subscribe/post?u=cb8b56e9d6a1cb1696cecc673&id=1a76961630 which appears to be mailchimp.

The problem looks to be the form submit on this line, which I guess needs to be corrected:

https://github.com/apache/groovy-website/blob/master/site/src/site/pages/groovy-weekly.groovy#L41

**Comment by paulk-asert** [comment]
We don't support signing up to the newsletter anymore since it isn't active - we have moved onto other mailing lists/slack/blog sites. I changed the pages to remove the form. Sorry for the inconvenience.

**Comment by dtt101** [comment]
No problem - thanks for the clarification.
